### ISSUE TITLE
Add a sponsors page to the website

### ISSUE THREAD

**Issue by bhavin192** [pythonpune/website-theme#2]
Have a page listing our sponsors. This will have name, logo (currently we have only 120x90px logos), link to their site, and how they helped us. More or less same details which are on meetup.com page.

## Implementation
Maybe we can have a partial and a page layout in the theme. And in the content repository, we will just create a `.md` file which uses this layout.
### website-theme changes
- Add `layouts/page/sponsors.html` with:
  ```html
  {{ define "main" }}
  HTML content or calls to partials here.
  {{ end }}
- This will utilize the `.Site.Data.sponsors` to load the data, and iterate over it.

### meetup-talks changes
- Add `content/sponsors.md` with:
  ```markdown
  type: page
  layout: sponsors
  ```
- Add `data/sponsors.yaml` with data:
  ```yaml
  - name: ACME org
    url: https://example.com
    sponsorship: Venue sponsor
    logo: <link to the logo> # need to decide the dimensions here.
  ```
Reference: https://stackoverflow.com/a/37515023
